### ISSUE TITLE
类型论为什么叉了，是大佬不打算学了吗

### ISSUE THREAD

**Issue by ice1000** [Marcythm/Marcythm#1]
https://github.com/Marcythm/Marcythm/blob/2904548cc4acbff57d4fc63b18f5ea71d96783a2/README.md?plain=1#L14

这里。很难过类型论领域失去了大佬这样潜在的人才 ：(

**Comment by Marcythm** [comment]
按照回忆的话，之前是觉得类型论太 abstract nonsense 了，感觉教材们的叙述似乎 highly dependent on 一些发展了很久 *but 比较抽象* 的东西，导致学的时候在这种抽象里迷失而不知道这和要研究的东西有啥关系；现在回头看或许只是以前不懂学习的方法，吸收知识但是把握不到核心要点没法组成框架。
现在感觉漫无目的地学一些东西也挺好的。。慢慢形成一些 insight，但与社会的发展节奏加诸于个人的力相冲突是最大的问题。
另一个促使我改变主要学习方向的因素还是国内发展环境的问题吧，type theory 的话连初步的导师都找不到，只靠自己且不够天才的话做出一些东西太艰难了。。如果能够成为 researcher 的话还是很愿意继续学一些这方面的东西的 :) ~~现阶段只能当做白月光了~~

**Comment by ice1000** [comment]
大佬有具体问题可以问我💅大佬加油⛽
